rediti/common/urls.py
from django.urls import path

from common.views import HomeView

app_name = 'common'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

rediti/rediti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('users.urls')),
]

rediti/common/models.py
from django.db import models

class IndexedTimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

rediti/subs/models.py
from django.db import models
from common.models import IndexedTimeStampedModel

class Thread(IndexedTimeStampedModel):
    title = models.CharField(max_length=50)
    author = models.ForeignKey('users.User', related_name="threads", on_delete=models.CASCADE)
    subrediti = models.ForeignKey('Subrediti', related_name="threads", on_delete=models.CASCADE)
    vote_count = models.IntergerField(default=0)

    class Meta:
        ordering = ['-created']

    def __str__(self)
        return self.title

class Subrediti(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    creator = models.ForeignKey('users.User', related_name="threads", on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self)
        return self.title

class Post(IndexedTimeStampedModel):
    content = models.TextField()
    author = models.ForeignKey('users.User', related_name="posts", on_delete=models.CASCADE)
    thread = models.ForeignKey('Thread', related_name="posts", on_delete=models.CASCADE)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return ("{} - {} - {}").format(self.id, self.thread, self.author)

class Subscription(models.Model):
    subrediti = models.ForeignKey('Subrediti', on_delete=models.CASCADE)
    users = models.ForeignKey('users.User', on_delete=models.CASCADE)
    subscribed = models.BooleanField(default=False)

    class Meta:
        unique_together = [('user','sub')]

    class __str__(self):
        return('{} - {}').format(self.subrediti, self)

rediti/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from common.models import IndexedTimeStampedModel
from .manager import UserManager

class User(AbstractBaseUser, PermissionsMixin, IndexedTimeStampedModel):
    email = models.EmailField("E-mail",unique=True)
    userame = models.CharField("Nome do usuário",max_length = 30, unique = True)
    description = models.TextField("Descrição",blank=True)
    karma = models.IntegerField(default=0)
    avatar = models.ImageField(blank=True, default = 'veigão.jpeg')
    is_staff = models.BooleanField("O boy é STAFF?",default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    
    def __str__(self):
        return self.userame

rediti/common/views.py
from django.shortcuts import render
from django.views import generic

class HomeView(generic.TemplateView):
    template_name = 'home.html'

rediti/subs/views.py
from django.shortcuts import render

# Create your views here.

rediti/users/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth import views
from .models import User

class ProfileView(generic.DetailView):
    template_name = "users/profile.html"
    model = User

class LogoutView(views.LogoutView):
    success_url = reverse('cammon:home')
    

rediti/templates/base.html
{% load static %}
<html>
    <head>
        <title>Rediti</title>
        <link href="{% static 'style.css' %}" rel="stylesheet">
    </head>

    <body>
        {% include 'navbar.html' %}
        <div class="container">
            {% block body %} {% endblock %}
        </div>
        <footer>
            <span>Rediti feito nas Férias de Alto Impacto 2019.1</span>
        </footer>
    </body>
</html>

rediti/templates/home.html
{% extends 'base.html' %}

rediti/templates/navbar.html
<div class="navbar">
    <a href="/"> <img src="https://logodownload.org/wp-content/uploads/2018/02/reddit-logo.png" alt=""> LOGO AQUI </a>
    <div class="nav-area">
        {% if user.is_authenticated %}
            <ul class="nav-list">
                <a href="{% url 'common:home' %}"> <li>Home</li> </a>
                <a class="nav-link" href=""> <li>profile</li> </a>
                <a class="nav-link" href="{% url 'users:logout' %}"></a>
            </ul>
        {% else %}
            <a class="nav-link" href="{% url 'users:singup' %}">Cadastro</a>
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
        {% endif %}


    </div>
</div>

rediti/templates/users/login.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <fieldset>
        {{ form.nom_field_errors }} {% for field in form %}
        <div>
            {{ field.label_tag }} {{ field }} {{  }}
        </div>
        {{% endfor %}}
        <button type="submit"> Login </button>
    </fieldset>
</form>

{% endblock %}

rediti/templates/users/profile.html
{% extends 'base.html' %}
{% block body %}

oiiiii

username: {{ user.username }}
email : {{ user.email }}
karma: {{ user.karma }}
avatar: <img src = "{{ user.avatar.url }}">

{% endblock %}